version: 1

# Кто является «базовой» компанией в отчёте Matrix (для строк "Δ(new − BASELINE)")
baselineCompetitor: DEMIDOV

# Настройки по конкурентам (можно переопределить baseUrl прямо тут)
competitors:
  AGRUPP:
    enabled: true
    baseUrl: "https://ag.market/catalog/truby-stalnye/truby-profilnye/"
    url:
      # как формировать slug размера для size-страниц:
      #   default       -> 40x20x1.5
      #   thicknessDash -> 40x20x1-5   (на AGRUPP так и нужно)
      sizeSlug: thicknessDash
  DEMIDOV:
    enabled: true
    baseUrl: "https://demidovsteel.ru/catalog/truby-profilnye/"
    url:
      sizeSlug: default

  # Заранее оставим карточки для будущих компаний — просто выключены
  KTZ:            { enabled: false }
  NTPZ:           { enabled: false }
  METALLSERVICE:  { enabled: false }
  METALLOTORG:    { enabled: false }
  DIPOS:          { enabled: false }

# Категории ассортимента
categories:

  # SP — профильные трубы
  SP:
    # Базовый пул размеров для категории (набор «по умолчанию» для всех компаний)
    all:
      - "25x25x1.5"
      - "40x40x1.5"
      - "40x20x1.5"
      - "50x25x1.5"

      - "25x25x2"
      - "40x40x2"
      - "60x60x2"
      - "80x80x2"
      - "40x20x2"
      - "50x25x2"
      - "60x40x2"

      - "60x60x3"
      - "80x80x3"
      - "60x40x3"

      # встречались в ТЗ, но часто нет на сайтах — оставим, можно вычеркнуть по конкуренту
      - "40x20x1.8"
      - "40x40x1.8"

    # Точечные переопределения по конкурентам (опционально)
    byCompetitor:
      AGRUPP:
        # если не указывать include/exclude — наследует sizes из all
        # примеры, как пользоваться:
        include:
        # можно добавить экзотические размеры, которых нет в all
        # - "30x30x2"
        exclude:
        # если на AGRUPP стабильно нет этих размеров — можно исключить
        # - "50x25x2"
        # - "60x40x2"

      DEMIDOV:
        include: [ ]
        exclude:
          # пока демидов не отдаёт эти позиции (по логам) — исключим
          - "40x20x1.8"
          - "40x40x1.8"
          # при необходимости сузить мониторинг:
          # - "50x25x1.5"
          # - "50x25x2"
          # - "60x40x2"