# Единый каталог размеров (канонические записи) — используйте те,
# которые хотите видеть в отчёте и для сравнения.
catalogSizes:
  - "20x20"
  - "25x25"
  - "30x30"
  - "40x20"
  - "40x40"
  - "50x25"
  - "60x40"
  - "60x60"
  - "80x80"
  - "100x100"
  - "120x120"

# Синонимы написания размеров -> к канону.
# ВАЖНО: кириллическую «х» тоже нормализуем. Если встречаются новые варианты — просто добавьте сюда.
synonyms:
  "20х20": "20x20"
  "20 x 20": "20x20"
  "25х25": "25x25"
  "25 x 25": "25x25"
  "30х30": "30x30"
  "30 x 30": "30x30"

  "40х20": "40x20"
  "40 x 20": "40x20"
  "40Х20": "40x20"

  "40х40": "40x40"
  "40 x 40": "40x40"
  "40Х40": "40x40"

  "50х25": "50x25"
  "50 x 25": "50x25"

  "60х40": "60x40"
  "60 x 40": "60x40"
  "60Х40": "60x40"

  "60х60": "60x60"
  "60 x 60": "60x60"

  "80х80": "80x80"
  "80 x 80": "80x80"

  "100х100": "100x100"
  "100 x 100": "100x100"

  "120х120": "120x120"
  "120 x 120": "120x120"

# Синонимы толщин -> к канону. Если магазины пишут «mm» или без пробела — добавьте варианты.
thicknessSynonyms:
  "1 мм": "1.0 мм"
  "1мм": "1.0 мм"
  "1.0мм": "1.0 мм"
  "1.0 mm": "1.0 мм"

  "1,5 мм": "1.5 мм"
  "1.5мм": "1.5 мм"
  "1,5мм": "1.5 мм"
  "1.5 mm": "1.5 мм"

  "2мм": "2.0 мм"
  "2 мм": "2.0 мм"
  "2,0 мм": "2.0 мм"
  "2.0мм": "2.0 мм"
  "2.0 mm": "2.0 мм"

  "2,5 мм": "2.5 мм"
  "2.5мм": "2.5 мм"
  "2.5 mm": "2.5 мм"

  "3мм": "3.0 мм"
  "3 мм": "3.0 мм"
  "3,0 мм": "3.0 мм"
  "3.0мм": "3.0 мм"
  "3.0 mm": "3.0 мм"

  "4мм": "4.0 мм"
  "4 мм": "4.0 мм"
  "4,0 мм": "4.0 мм"
  "4.0мм": "4.0 мм"
  "4.0 mm": "4.0 мм"