app:
  # Куда писать Excel-отчёт
  exportPath: report.xlsx

  # Где лежит конфиг размеров (наш YAML)
  # можно: classpath:config/sizes.yml  или file:./config/sizes.yml
  sizesResource: classpath:config/sizes.yml

  # Санити-фильтр цен (игнорируем слишком маленькие/большие)
  minPrice: 20000
  maxPrice: 300000

  # Какие конкуренты включены в прогоне (по enum-имени)
  competitorsEnabled:
    - DEMIDOV
    - AGRUPP

  # Базовые URL для парсеров (можно править не трогая код)
  competitorsBaseUrls:
    DEMIDOV: "https://demidovsteel.ru/catalog/truby-profilnye/"
    AGRUPP: "https://ag.market/catalog/truby-stalnye/truby-profilnye/"


# Логи: делаем наш пакет информативным, а спринг не шумным
logging:
  level:
    root: INFO
    org.springframework: WARN
    com.company.parser: INFO